baseurl = "https://nshelton.github.io"
title = "SHELTRON"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-26353276-1"

[taxonomies]
  category = "categories"

[params]

  [related]

  threshold = 80
  includeNewer = true
  toLower = false

  [[related.indices]]
  name = "categories"
  weight = 100

  # Use custom.css for your custom styling
  style = "sea"
  description = "Sheltron visuals portfolio site"
  copyright = "&copy;2020 Sheltron Visuals"
  sidebarAbout = [
    "Freelance graphics programming, Art, Code, Math, Data"
  ]
  email = "nshelton@gmail.com"

  # Nav links in the side bar

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Resources"
  url = "resources/"

  [[params.navlinks]]
  name = "All Projects"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Live Demos"
  url = "demos/"


  [params.social]
  # facebook      = "full page or profile url in facebook"
  email         = "nshelton@gmail.com"
  twitter       = "https://twitter.com/Sheltron3030"
  linkedin      = "https://www.linkedin.com/in/ngshelton/"
  instagram     = "https://www.instagram.com/nshelton"
  github        = "https://github.com/nshelton"
  # youtube       = "full profile url in youtube"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
 