baseurl = "https://sheltron.netlify.com"
title = "sheltron visuals "
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-26353276-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Sheltron visuals portfolio site"
  copyright = "&copy;2020 Sheltron Visuals"
  sidebarAbout = [
    "Freelance graphics programming, Art, Code, Math"
  ]
  email = "nshelton@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Projects"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Resources"
  url = "resources/"

  [params.social]
  # facebook      = "full page or profile url in facebook"
  email         = "nshelton@gmail.com"
  twitter       = "https://twitter.com/Sheltron3030"
  linkedin      = "https://www.linkedin.com/in/ngshelton/"
  instagram     = "https://www.instagram.com/nshelton"
  github        = "https://github.com/nshelton"
  # youtube       = "full profile url in youtube"

